name: PyPI release

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build setuptools twine

    - name: Build and upload esp-idf-nvs-partition-gen ${{ github.event.release.tag_name }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PROJECT_TOKEN }}
      run: |
        pip install .
        PUBLISHED_VERSION=$(curl https://pypi.org/pypi/esp-idf-nvs-partition-gen/json 2>/dev/null | jq -r '.info.version')
        CURRENT_VERSION=$(python -c "from esp_idf_nvs_partition_gen import __version__; print(__version__)")
        if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Version ${PUBLISHED_VERSION} already published, skipping..."
          exit 0
        else
          echo "Packaging and publishing new esp-idf-nvs-partition-gen version: ${CURRENT_VERSION}"
          python -m build
          twine check dist/* && twine upload dist/*
        fi
